### PR TITLE
create stations dashboard

### PR DESCRIPTION
**Pull request by rickyamparo**
@blsrofe @Aram-Anderson @JoelLindow 
Created a stations.erb and an all.erb. 
stations.erb displays a dashboard where you can select how you want to display the stations. 
all.erb displays all of the stations in a list. 

Should we have a folder for all of the stations view? or should we append these views with "station"?

Added routes in bike_share_app.rb

### CODE REVIEW

**Comment by blsrofe** [comment]
I asked Ilana about that the other day and she said having folders inside views that each have a new, show, etc was the way to go. I think we should wait till you get here to change that though because I have a feeling that may cause some major merge issues with the branch Aram and I are working on. We are making a station_dashboard.erb file for iteration 3

**Comment by blsrofe** [comment]
I wonder if your station dashboard intro page should be part of the station dashboard aram and I are working on and instead your page is just the index and show pages that the dashboard page redirects too. Otherwise I think we are going to end up with two different station dashboards. Look at iteration 3 if that doesn't make sense.

**Comment by rickyamparo** [comment]
@blsrofe  Both comments make perfect sense. I'll hold off on making the station specific views folder. As for the dashboard, I was pictured a place where you can then click on a number of links that will each organize the stations database in different ways. All.erb would just be a link in the dashboard that displays all stations by id.

**Comment by blsrofe** [comment]
OK I get it. One of the links on your dashboard would link to the analytics dashboard. Is that right?

**Comment by rickyamparo** [comment]
That's exactly what I was envisioning.

**Pull request merged**
