### PR TITLE
did some pretty sweet stuff involving a button and a lot of wasted time

### PR DESCRIPTION
**Pull request by JoelLindow**

### CODE REVIEW

**Comment by Aram-Anderson** [comment]
I see you didn't move your waffle card. Please move your waffle card in the future.

**Comment by JoelLindow** [comment]
THERE WAS NO WAFFLE CARD! STOP TRYING TO TRIGGER ME!

**Comment by Aram-Anderson** [comment]
I see you didn't move your waffle card. Please move your waffle card in the future. Just felt I need to reiterate that point.

**Comment by JoelLindow** [comment]
For somebody with such a short attention span, I'm shocked you could remember what you said long enough to repeat it.

**Comment by Aram-Anderson** [comment]
I actually had to review the comment to see what I was mad about. But now I'm mad again.

**Comment by JoelLindow** [comment]
If you need a ride to your psych appointment later this week let me know. Quitting meds for your memory against doctors recommendation is not anything to play with. I care about you, buddy. Just want to see you feeling better. I'll slack you my phone number. Let me know if you need anything. I'm here to help.

**Comment by Aram-Anderson** [comment]
What are we talking about???

**Comment by JoelLindow** [comment]
That's what I'm saying man. We need to get you a refill.

**Pull request merged**
